spring.application.name=learn-spring-framework
# DEBUG shows Spring's bean creation and auto-configuration decisions.
logging.level.org.springframework=error


# Application Properties

currency-service.url=http//dev.in28minutes.com
currency-service.username=devusername
currency-service.key=devkey